# Generated by Django 4.1.4 on 2023-02-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
