# Generated by Django 4.1.4 on 2023-02-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_tag_post_tags_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='capiton',
            new_name='caption',
        ),
    ]
