# Generated by Django 4.1.4 on 2023-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
